const data = {
    products: [
        {
            name: 'OnePlus 9RT 5G',
            id: 1,
            slug: 'oneplus-9rt-5g',
            category: 'Mobiles',
            image: '/images/mobile1.jpg',
            price: 489,
            brand: 'OnePlus',
            rating: 4.3,
            numReviews: 10535,
            countInStock: 4,
            description: 'The Shape of Power. The innate power within is characterized by a sleek, sculpted design imbued with lean elegance. Every line emphasizes speed with flair. Confident curves create light and shadows hinting at the power below the surface. Push the boundaries with design engineered for pure speed. OnePlus Games, Respond faster, amp up your Wi-Fi, feel every move. When it comes to next-level mobile gaming on the OnePlus 9RT, always play to win. Make Moments Magical. Co-developed with SONY, the IMX766 sensor elevates night photography. Together with OIS and the Nightscape algorithm, low-light photography features significantly less blur and noise. Colors come alive with brighter scenes for photos and videos with virtually little to no washed-out overexposure. It is time to make over and under-exposed videos a thing of the past. Speed matters. A large 4,500 mAh battery uses our fastest ever dual-cell charging technology. Accelerate from 0-100% in just 29 minutes.',
        },
        {
            name: 'Samsung S20 FE 5G',
            id: 2,
            slug: 'samsung-s20-fe-5g',
            category: 'Mobiles',
            image: '/images/mobile2.jpg',
            price: 475,
            brand: 'Samsung',
            rating: 4.4,
            numReviews: 20577,
            countInStock: 20,
            description: 'With a Triple pro-grade camera, smooth 120Hz refresh rate display, and an all-day intelligent battery that charges up in minutes, the Samsung Galaxy S20 FE 5G delivers outstanding innovation. The Triple-lens camera system will not only take bright and high quality images and videos, but can also zoom in from afar, thanks to the 30X Space Zoom. The single take AI mode will let you capture multiple images and videos with just a touch of a button. Shooting at night? No problem. With the help of Night Mode, the Galaxy S20 FE 5G phone can capture crystal-clear images without flash. The Samsung Galaxy S20 FE 5G series is tailor-made for those who want the latest technology without compromise. Choose from a wide range of six colorful hues in a sleek matte finish. Battery power consumption depends on usage patterns and results may vary.',
        },
        {
            name: 'Google Pixel 6A',
            id: 3,
            slug: 'google-pixel-6a',
            category: 'Mobiles',
            image: '/images/mobile3.jpg',
            price: 639,
            brand: 'Google',
            rating: 4.2,
            numReviews: 141,
            countInStock: 0,
            description: 'Meet Pixel 6a, the more affordable Google phone that adapts to you. Powered by Google Tensor, it is super fast and secure, with an amazing battery and camera. And it is an unlocked Android smartphone, so you can choose the data plan and carrier that work for you. LEGAL Works with all major carriers. 5G service is carrier dependent. Requires a 5G data plan (sold separately). 5G service not available on all carrier networks or in all areas. Contact carrier for details. 5G service, speed and performance depend on many factors, including carrier network capabilities and signal strength. Actual results may vary. Some features not available in all areas. Data rates may apply. Estimated battery life based on testing using a median Pixel user battery usage profile across a mix of talk, data, standby, and use of other features. Average battery life during testing was approximately 29 hours. Battery life depends upon many factors and usage of certain features will decrease battery life.',
        },
        {
            name: 'Airpods Pro',
            id: 4,
            slug: 'airpods-pro',
            category: 'Earphones',
            image: '/images/earphone1.jpg',
            price: 169,
            brand: 'Apple',
            rating: 4.8,
            numReviews: 297841,
            countInStock: 0,
            description: 'AirPods Pro take the listening experience to a new level of individuality. Personalized Spatial Audio with dynamic head tracking works with all your devices to immerse you deeper in all-around-you sound. And Adaptive EQ accounts for the fit of AirPods Pro, so you hear every frequency just as it was intended. From instant setup to Siri commands, AirPods Pro hold all the qualities that make the AirPods family so magical. And new features give you the ability to move through more tasks with unprecedented ease.',
        },
        {
            name: 'LG TONE Free FP9',
            id: 5,
            slug: 'lg-tone-free-fp9',
            category: 'Earphones',
            image: '/images/earphone2.jpg',
            price: 137,
            brand: 'LG',
            rating: 4.3,
            numReviews: 1420,
            countInStock: 20,
            description: 'Free your travel with the LG TONE Free FP9. Connect to in-flight entertainment systems even without Bluetooth capabilities. Get peace of mind with a UVnano charging case that kills 99% of bacteria on the speaker mesh* and medical grade ear gels. Plus, get better clarity for calls on the go. Disclaimers: *UVnano is a compound word derived from the words UV and its unit nanometer. Independent testing shows the UVnano charging case kills 99.9% of bacteria on the speaker mesh of the earbuds in five minutes while charging. The UV LED function works only when the charging case is connected to the power cable.',
        },
        {
            name: 'SONY Link Buds',
            id: 6,
            slug: 'sony-link-buds',
            category: 'Earphones',
            image: '/images/earphone3.jpg',
            price: 130,
            brand: 'Sony',
            rating: 3.7,
            numReviews: 2047,
            countInStock: 20,
            description: 'Link your online and offline worlds with headphones that keep you in both. The all-new Sony Link Buds feature a comfortable open-ring design that naturally blends natural and digital sound. Stay authentically connected to everyday life while listening to music, taking calls, gaming, and more, all with dynamic sound.',
        },
    ],
};
export default data;